export const GET_PEOPLE = 'GET_PEOPLE';

export const SET_WEATHER = 'SET_WEATHER';
export const SET_UNIT_OF_MEASURE = 'SET_UNIT_OF_MEASURE';

export const SET_SLIDER_TAB_INDEX = 'SET_SLIDER_TAB_INDEX';

export const PRELOADER_GLOBAL_OPEN = 'PRELOADER_GLOBAL_OPEN';

export const CLEAN_WEATHER = 'CLEAN_WEATHER';

export const RESET_SLIDER_TAB_INDEX = 'RESET_SLIDER_TAB_INDEX';